/**
 * Генератор TypeBox-схем из спецификации OpenAPI (ADR 0002).
 *
 * Одна из двух частей команды `codegen` пакета backend: вторая — типы
 * `openapi-typescript`. Схемы подставляются в роуты Elysia как валидация
 * body/params и сериализация ответов.
 *
 * Запуск: bun scripts/openapi-to-typebox.ts <openapi.yaml> <output.ts>
 */

type Json = Record<string, unknown>

// Файл — модуль: скрипту нужны top-level await.
export {}

const REF_PREFIX = "#/components/schemas/"
const IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/

const [input, output] = process.argv.slice(2)
if (!input || !output) {
  console.error("Usage: bun scripts/openapi-to-typebox.ts <openapi.yaml> <output.ts>")
  process.exit(1)
}

const openapi = (await Bun.YAML.parse(await Bun.file(input).text())) as {
  components?: { schemas?: Record<string, Json> }
  paths?: Record<string, Json>
}

const components = openapi.components?.schemas
if (!components || Object.keys(components).length === 0) {
  throw new Error(`В ${input} нет components.schemas`)
}

const names = Object.keys(components)
const emitted = topoSort(names, (name) => refsOf(components[name]))

const header = `/**
 * This file was auto-generated by scripts/openapi-to-typebox.ts from ${input}.
 * Do not make direct changes to the file.
 */

import { t } from 'elysia'
`

const exports_ = emitted
  .map((name) => {
    if (!IDENTIFIER.test(name)) {
      throw new Error(`Имя схемы не является идентификатором: ${name}`)
    }
    return `export const ${name} = ${emitType(components[name], 0)}`
  })
  .join("\n\n")

const parameters = emitParameters(openapi.paths ?? {})

await Bun.write(output, `${header}\n${exports_}\n\n${parameters}`)
console.log(`${input} → ${output} (${emitted.length} схем)`)

/** `$ref` вида `#/components/schemas/X` → имя сгенерированной константы `X`. */
function resolveRef(ref: string): string {
  if (!ref.startsWith(REF_PREFIX)) {
    throw new Error(`Неподдерживаемая ссылка: ${ref}`)
  }
  const name = ref.slice(REF_PREFIX.length)
  if (!IDENTIFIER.test(name)) {
    throw new Error(`Ссылка ведёт на не-идентификатор: ${ref}`)
  }
  return name
}

/** Схемы параметров операции (path/query/header), сгруппированные по operationId. */
function emitParameters(paths: Record<string, Json>): string {
  const methods = ["get", "post", "put", "patch", "delete"]
  const blocks: string[] = []

  for (const pathItem of Object.values(paths)) {
    const shared = (pathItem.parameters ?? []) as Json[]
    for (const method of methods) {
      const operation = pathItem[method] as Json | undefined
      if (!operation) continue
      const operationId = operation.operationId
      if (typeof operationId !== "string") continue

      const operationParameters = (operation.parameters as Json[] | undefined) ?? []
      const groups = new Map<string, string[]>()

      for (const parameter of [...shared, ...operationParameters]) {
        const location = parameter.in
        const name = parameter.name
        const schema = parameter.schema
        if (
          typeof location !== "string" ||
          typeof name !== "string" ||
          typeof schema !== "object" ||
          schema === null
        ) {
          throw new Error(`Неподдерживаемый параметр ${String(name)} в операции ${operationId}`)
        }
        const value = emitType(schema as Json, 4)
        const field = parameter.required === true ? value : `t.Optional(${value})`
        const lines = groups.get(location) ?? []
        lines.push(`      ${propertyKey(name)}: ${field},`)
        groups.set(location, lines)
      }

      if (groups.size === 0) continue
      const fields = [...groups].map(
        ([location, lines]) => `    ${location}: t.Object({\n${lines.join("\n")}\n    }),`,
      )
      blocks.push(`  ${operationId}: {\n${fields.join("\n")}\n  },`)
    }
  }

  if (blocks.length === 0) return ""
  return `export const parameters = {\n${blocks.join("\n")}\n} as const\n`
}

/** Ссылки `#/components/schemas/X`, использованные в схеме. */
function refsOf(schema: Json): string[] {
  const found = new Set<string>()
  const walk = (node: unknown): void => {
    if (Array.isArray(node)) {
      node.forEach(walk)
      return
    }
    if (typeof node !== "object" || node === null) return
    const value = node as Json
    if (typeof value.$ref === "string") {
      found.add(resolveRef(value.$ref))
    }
    Object.values(value).forEach(walk)
  }
  walk(schema)
  return [...found]
}

/** Топологическая сортировка: схема объявляется после всех, на кого ссылается. */
function topoSort(nodes: string[], dependencies: (node: string) => string[]): string[] {
  const pending = new Map(nodes.map((node) => [node, dependencies(node)]))
  const done = new Set<string>()
  const order: string[] = []

  while (pending.size > 0) {
    const ready = [...pending].filter(([, deps]) =>
      deps.every((dep) => done.has(dep) || !pending.has(dep)),
    )
    if (ready.length === 0) {
      throw new Error(`Циклические ссылки между схемами: ${[...pending.keys()].join(", ")}`)
    }
    for (const [node] of ready) {
      pending.delete(node)
      done.add(node)
      order.push(node)
    }
  }
  return order
}

function emitType(schema: Json, indent: number): string {
  if (typeof schema.$ref === "string") {
    return resolveRef(schema.$ref)
  }

  if (Array.isArray(schema.enum)) {
    const literals = schema.enum.map((value) =>
      typeof value === "string" ? `t.Literal(${quote(value)})` : `t.Literal(${String(value)})`,
    )
    return `t.Union([${literals.join(", ")}])`
  }

  switch (schema.type) {
    case "string":
      return withOptions("t.String", formatOptions(schema))
    case "integer":
      return withOptions("t.Integer", rangeOptions(schema))
    case "number":
      return withOptions("t.Number", rangeOptions(schema))
    case "boolean":
      return "t.Boolean()"
    case "array": {
      if (typeof schema.items !== "object" || schema.items === null) {
        throw new Error(`Массив без items: ${JSON.stringify(schema)}`)
      }
      return `t.Array(${emitType(schema.items as Json, indent)})`
    }
    case "object":
      return emitObject(schema, indent)
    default:
      throw new Error(`Неподдерживаемая схема: ${JSON.stringify(schema)}`)
  }
}

function emitObject(schema: Json, indent: number): string {
  const properties = (schema.properties ?? {}) as Json
  const required = new Set(Array.isArray(schema.required) ? (schema.required as string[]) : [])
  const inner = " ".repeat(indent + 2)

  const fields = Object.entries(properties).map(([name, property]) => {
    const value = emitType(property as Json, indent + 2)
    return `${inner}${propertyKey(name)}: ${required.has(name) ? value : `t.Optional(${value})`},`
  })

  const options: string[] = []
  if (schema.additionalProperties === false) {
    options.push("additionalProperties: false")
  }

  const close = " ".repeat(indent)
  const tail = options.length > 0 ? `, { ${options.join(", ")} }` : ""
  if (fields.length === 0) return `t.Object({}${tail})`
  return `t.Object({\n${fields.join("\n")}\n${close}}${tail})`
}

function formatOptions(schema: Json): string[] {
  return typeof schema.format === "string" ? [`format: ${quote(schema.format)}`] : []
}

function rangeOptions(schema: Json): string[] {
  const options: string[] = []
  for (const keyword of [
    "minimum",
    "maximum",
    "exclusiveMinimum",
    "exclusiveMaximum",
    "multipleOf",
  ]) {
    if (typeof schema[keyword] === "number") {
      options.push(`${keyword}: ${schema[keyword]}`)
    }
  }
  return options
}

/** Вызов TypeBox-фабрики с опциями или без них. */
function withOptions(factory: string, options: string[]): string {
  return options.length === 0 ? `${factory}()` : `${factory}({ ${options.join(", ")} })`
}

function quote(value: string): string {
  return `'${value.replaceAll("'", "\\'")}'`
}

/** Свойства без кавычек, если имя — корректный идентификатор TypeScript. */
function propertyKey(name: string): string {
  return IDENTIFIER.test(name) ? name : quote(name)
}
