/**
 * This file was auto-generated by scripts/openapi-to-typebox.ts from ../../contract/openapi.yaml.
 * Do not make direct changes to the file.
 */

import { t } from 'elysia'

export const Booking = t.Object({
  id: t.String({ format: 'uuid' }),
  eventTypeId: t.String({ format: 'uuid' }),
  startAt: t.String({ format: 'date-time' }),
  guestName: t.String(),
  guestEmail: t.String({ format: 'email' }),
})

export const BookingCreate = t.Object({
  eventTypeId: t.String({ format: 'uuid' }),
  startAt: t.String({ format: 'date-time' }),
  guestName: t.String(),
  guestEmail: t.String({ format: 'email' }),
})

export const ErrorBody = t.Object({
  error: t.Object({
    code: t.Union([t.Literal('VALIDATION_ERROR'), t.Literal('INVALID_ADMIN_PASSWORD'), t.Literal('EVENT_TYPE_NOT_FOUND'), t.Literal('SLOT_TAKEN')]),
    message: t.String(),
  }),
})

export const EventType = t.Object({
  id: t.String({ format: 'uuid' }),
  name: t.String(),
  description: t.String(),
  durationMinutes: t.Integer({ minimum: 1, maximum: 540 }),
})

export const EventTypeCreate = t.Object({
  name: t.String(),
  description: t.String(),
  durationMinutes: t.Integer({ minimum: 1, maximum: 540 }),
})

export const EventTypeRef = t.Object({
  id: t.String({ format: 'uuid' }),
  name: t.String(),
})

export const Slot = t.Object({
  startAt: t.String({ format: 'date-time' }),
  available: t.Boolean(),
})

export const Availability = t.Object({
  slots: t.Array(Slot),
})

export const BookingListItem = t.Object({
  eventType: EventTypeRef,
  startAt: t.String({ format: 'date-time' }),
})

export const EventTypeList = t.Object({
  eventTypes: t.Array(EventType),
})

export const BookingList = t.Object({
  bookings: t.Array(BookingListItem),
})

export const parameters = {
  EventTypes_create: {
    header: t.Object({
      'X-Admin-Password': t.String(),
    }),
  },
  EventTypes_get: {
    path: t.Object({
      id: t.String(),
    }),
  },
  EventTypes_availability: {
    path: t.Object({
      id: t.String(),
    }),
  },
} as const
