/**
 * This file was auto-generated by scripts/openapi-to-sdk.ts from ../../contract/openapi.yaml.
 * Do not make direct changes to the file.
 *
 * SDK клиент API: путь, метод, заголовки и тело операции взяты из контракта,
 * транспорт (JSON и конверт ошибок) — в `./client`.
 */

import { postJson, request } from './client'
import type { operations } from './schema'

/** Ключи успешных (2xx) ответов операции: `200`, `201`, … */
type SuccessStatus<Responses> = keyof Responses extends never
  ? never
  : ExtractStatus<keyof Responses>

type ExtractStatus<Status> = Status extends number | string
  ? `${Status}` extends `2${string}`
    ? Status
    : never
  : never

type JsonOf<Response> = Response extends { content: infer Content }
  ? Content extends { 'application/json': infer Body }
    ? Body
    : never
  : never

/** Тело успешного ответа операции, выведенное из контракта. */
export type ResponseBody<Op> = Op extends { responses: infer Responses }
  ? JsonOf<Responses[SuccessStatus<Responses>]>
  : never

/** Тело запроса операции (`application/json`), выведенное из контракта. */
export type RequestBody<Op> = Op extends { requestBody: infer Body }
  ? Body extends { content: infer Content }
    ? Content extends { 'application/json': infer JsonBody }
      ? JsonBody
      : never
    : never
  : never

/** Операция `Bookings_list`: `GET /api/bookings`. */
export function listBookings(): Promise<ResponseBody<operations['Bookings_list']>> {
  return request('/api/bookings')
}

/** Операция `Bookings_create`: `POST /api/bookings`. */
export function createBooking(
  body: RequestBody<operations['Bookings_create']>,
): Promise<ResponseBody<operations['Bookings_create']>> {
  return postJson('/api/bookings', body)
}

/** Операция `EventTypes_list`: `GET /api/event-types`. */
export function listEventTypes(): Promise<ResponseBody<operations['EventTypes_list']>> {
  return request('/api/event-types')
}

/** Операция `EventTypes_create`: `POST /api/event-types`; заголовок `X-Admin-Password`. */
export function createEventType(
  body: RequestBody<operations['EventTypes_create']>,
  adminPassword: string,
): Promise<ResponseBody<operations['EventTypes_create']>> {
  return postJson('/api/event-types', body, { 'X-Admin-Password': adminPassword })
}

/** Операция `EventTypes_get`: `GET /api/event-types/{id}`. */
export function getEventType(id: string): Promise<ResponseBody<operations['EventTypes_get']>> {
  return request(`/api/event-types/${id}`)
}

/** Операция `EventTypes_availability`: `GET /api/event-types/{id}/availability`. */
export function getEventTypeAvailability(
  id: string,
): Promise<ResponseBody<operations['EventTypes_availability']>> {
  return request(`/api/event-types/${id}/availability`)
}
