/**
 * Генератор клиентского SDK из спецификации OpenAPI (паттерн ADR 0002).
 *
 * Одна из двух частей команды `codegen` пакета frontend: вторая — типы
 * `openapi-typescript`. SDK фиксирует операции API (путь, метод, заголовки,
 * тело), транспорт — JSON и конверт ошибок — остаётся в `src/api/client`.
 *
 * Запуск: bun scripts/openapi-to-sdk.ts <openapi.yaml> <output.ts>
 */

type Json = Record<string, unknown>

type Parameter = {
  name: string
  in: string
  required?: boolean
  schema?: Json
}

type Emitted = {
  /** Функция SDK с документацией. */
  source: string
  /** Какой транспорт вызывает операция: `request` (GET) или `postJson` (POST). */
  transport: 'request' | 'postJson'
}

// Файл — модуль: скрипту нужны top-level await.
export {}

/** HTTP-методы контракта; неподдерживаемый метод роняет кодоген. */
const HTTP_METHODS = ['get', 'post'] as const

/** Действия после которых остаётся множественное число ресурса (list → listEventTypes). */
const PLURAL_ACTIONS = new Set(['list'])

/** Действия после которых берётся единственное число ресурса (create → createEventType). */
const ITEM_ACTIONS = new Set(['get', 'create', 'update', 'delete', 'patch', 'put', 'remove'])

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/
const OPERATION_ID = /^[A-Za-z]+_[A-Za-z]+$/
const PATH_PARAM = /\{([A-Za-z0-9_]+)\}/g
const SUCCESS_STATUS = /^2\d\d$/
const MAX_LINE = 100

const [input, output] = process.argv.slice(2)
if (!input || !output) {
  console.error('Usage: bun scripts/openapi-to-sdk.ts <openapi.yaml> <output.ts>')
  process.exit(1)
}

const openapi = (await Bun.YAML.parse(await Bun.file(input).text())) as {
  paths?: Record<string, Json>
}

const paths = openapi.paths
if (!paths || Object.keys(paths).length === 0) {
  throw new Error(`В ${input} нет paths`)
}

const functions: string[] = []
const transports = new Set<string>()

for (const [path, pathItem] of Object.entries(paths)) {
  const item = pathItem as Record<string, Json>
  for (const method of HTTP_METHODS) {
    const operation = item[method]
    if (operation === undefined) continue
    const emitted = emitOperation(path, method, operation as Json)
    transports.add(emitted.transport)
    functions.push(emitted.source)
  }
}

const header = `/**
 * This file was auto-generated by scripts/openapi-to-sdk.ts from ${input}.
 * Do not make direct changes to the file.
 *
 * SDK клиент API: путь, метод, заголовки и тело операции взяты из контракта,
 * транспорт (JSON и конверт ошибок) — в \`./client\`.
 */

import { ${[...transports].sort().join(', ')} } from './client'
import type { operations } from './schema'

/** Ключи успешных (2xx) ответов операции: \`200\`, \`201\`, … */
type SuccessStatus<Responses> = keyof Responses extends never
  ? never
  : ExtractStatus<keyof Responses>

type ExtractStatus<Status> = Status extends number | string
  ? \`\${Status}\` extends \`2\${string}\`
    ? Status
    : never
  : never

type JsonOf<Response> = Response extends { content: infer Content }
  ? Content extends { 'application/json': infer Body }
    ? Body
    : never
  : never

/** Тело успешного ответа операции, выведенное из контракта. */
export type ResponseBody<Op> = Op extends { responses: infer Responses }
  ? JsonOf<Responses[SuccessStatus<Responses>]>
  : never

/** Тело запроса операции (\`application/json\`), выведенное из контракта. */
export type RequestBody<Op> = Op extends { requestBody: infer Body }
  ? Body extends { content: infer Content }
    ? Content extends { 'application/json': infer JsonBody }
      ? JsonBody
      : never
    : never
  : never
`

await Bun.write(output, `${header}\n${functions.join('\n\n')}\n`)
console.log(`${input} → ${output} (${functions.length} операций)`)

/** Операция контракта: документация, сигнатура и вызов транспорта. */
function emitOperation(path: string, method: string, operation: Json): Emitted {
  const operationId = String(operation.operationId ?? '')
  if (!OPERATION_ID.test(operationId)) {
    throw new Error(`operationId не поддерживается генератором: ${operationId || '<нет>'}`)
  }

  const pathArgs: string[] = []
  const headers: { header: string; arg: string }[] = []
  for (const param of (operation.parameters ?? []) as Parameter[]) {
    if (param.required !== true) {
      throw new Error(`Необязательный параметр не поддерживается генератором: ${param.name}`)
    }
    if (!IDENTIFIER.test(param.name) && param.in === 'path') {
      throw new Error(`Имя параметра не является идентификатором: ${param.name}`)
    }
    if (param.schema?.type !== 'string') {
      throw new Error(`Параметр не строкового типа не поддерживается генератором: ${param.name}`)
    }
    if (param.in === 'path') {
      pathArgs.push(`${param.name}: string`)
    } else if (param.in === 'header') {
      headers.push({ header: param.name, arg: headerArg(param.name) })
    } else {
      throw new Error(`Параметры in: ${param.in} не поддерживаются генератором: ${param.name}`)
    }
  }

  const hasBody = operation.requestBody !== undefined
  if (
    hasBody &&
    (operation.requestBody as { content?: Json }).content?.['application/json'] === undefined
  ) {
    throw new Error(`Тело операции ${operationId} не в формате application/json`)
  }

  const responses = (operation.responses ?? {}) as Record<string, Json>
  if (!Object.keys(responses).some((status) => SUCCESS_STATUS.test(status))) {
    throw new Error(`У операции ${operationId} нет успешного (2xx) ответа`)
  }

  const args = [
    ...pathArgs,
    ...(hasBody ? [`body: RequestBody<operations['${operationId}']>`] : []),
    ...headers.map(({ arg }) => `${arg}: string`),
  ]
  const name = functionName(operationId)
  const call = emitCall(path, method, hasBody, headers)
  const responseType = `Promise<ResponseBody<operations['${operationId}']>>`
  const head = `export function ${name}(${args.join(', ')}): ${responseType}`
  const body =
    head.length + 3 <= MAX_LINE
      ? `${head} {\n  return ${call.source}\n}`
      : [
          `export function ${name}(`,
          ...args.map((arg) => `  ${arg},`),
          `): ${responseType} {`,
          `  return ${call.source}`,
          '}',
        ].join('\n')
  const doc = `/** Операция \`${operationId}\`: \`${method.toUpperCase()} ${path}\`${describeHeaders(headers)}. */`

  return { source: `${doc}\n${body}`, transport: call.transport }
}

/** Вызов транспорта: GET → `request`, POST → `postJson` с заголовками операции. */
function emitCall(
  path: string,
  method: string,
  hasBody: boolean,
  headers: { header: string; arg: string }[],
): { source: string; transport: Emitted['transport'] } {
  const templated = path.replace(PATH_PARAM, (_match, name: string) => `\${${name}}`)
  const url = templated === path ? `'${path}'` : `\`${templated}\``

  if (method === 'get') {
    return { source: `request(${url})`, transport: 'request' }
  }
  const headerMap =
    headers.length > 0
      ? `{ ${headers.map(({ header, arg }) => `'${header}': ${arg}`).join(', ')} }`
      : null
  const parts = [hasBody ? 'body' : null, headerMap].filter((part): part is string => part !== null)
  return {
    source: `postJson(${url}${parts.length > 0 ? `, ${parts.join(', ')}` : ''})`,
    transport: 'postJson',
  }
}

/** Документация заголовков: «; заголовок `X-Admin-Password`». */
function describeHeaders(headers: { header: string }[]): string {
  if (headers.length === 0) return ''
  const list = headers.map(({ header }) => `\`${header}\``).join(', ')
  return `; заголовок${headers.length > 1 ? 'и' : ''} ${list}`
}

/** `EventTypes_list` → `listEventTypes`, `EventTypes_availability` → `getEventTypeAvailability`. */
function functionName(operationId: string): string {
  const [resource, action] = operationId.split('_')
  if (PLURAL_ACTIONS.has(action)) return `${action}${resource}`
  if (ITEM_ACTIONS.has(action)) return `${action}${singular(resource)}`
  return `get${singular(resource)}${action[0].toUpperCase()}${action.slice(1)}`
}

/** `EventTypes` → `EventType`, `Bookings` → `Booking`. */
function singular(resource: string): string {
  return resource.endsWith('s') && resource.length > 1 ? resource.slice(0, -1) : resource
}

/** `X-Admin-Password` → `adminPassword`: имя аргумента функции SDK. */
function headerArg(header: string): string {
  const parts = header
    .replace(/^x-/i, '')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
  const name = parts
    .map((part, index) =>
      index === 0 ? part.toLowerCase() : part[0].toUpperCase() + part.slice(1),
    )
    .join('')
  if (!IDENTIFIER.test(name)) {
    throw new Error(`Имя заголовка не превращается в идентификатор: ${header}`)
  }
  return name
}
